/* AUSOAI R2: compact home restoration; existing editor/runtime remain unchanged. */
(()=>{'use strict';
const BASE=new URL('.',document.currentScript.src||location.href),A=window.HUB_ASSETS||(window.HUB_ASSETS={});let initialized=false,selected='all',home=null,queued=false;
const $=s=>document.querySelector(s),safe=v=>{try{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password?u.href:''}catch{return ''}},esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const groups=[
['today','오늘 바로 쓰기','휴대폰 기본 기능 · AUSOAI Daily',[
['mic','AUSOAI 마이크','눌러서 한 번 듣기 · 이후 무음 대기','auso'],['daily','AUSOAI Daily','일정·메모·메일·파일','auso'],['phone','전화','전화 앱','Green'],['sms','문자','메시지 앱','Blue'],['contacts','연락처','연락처 선택','Pink'],['camera','카메라','사진 촬영','Gold'],['photos','사진','갤러리','Coral'],['files','파일','파일 선택','Blue'],['alarm','알람','시계·알람','Gold'],['calc','계산기','계산 앱/웹','Green'],['chrome','Chrome','Google 브라우저','Blue'],['sinternet','Samsung Internet','삼성 브라우저','Violet'],['snotes','Samsung Notes','메모·노트','Gold'],['schedule','일정관리','추가·수정·완료·ICS','auso']]],
['edit','만들기 · 편집','저장 · 취소 · 되돌리기 · 내보내기',[
['docpdf','문서 · PDF','음성 편집·Word/PDF','auso'],['word','Microsoft Word','앱 우선 · 웹 연결','Blue'],['photoedit','사진 빠른편집','이미지 작업','auso'],['canva','Canva','디자인 웹 편집','Cyan'],['capcut','CapCut','영상 웹 편집','Violet'],['music','뮤직 스튜디오','가사·음원·저장·내보내기','auso'],['export','내보내기 센터','SNS·파일·공유','auso'],['bizcard','명함 · 홍보물','디자인·저장·공유','auso']]],
['mail','메일 · 클라우드 · 오피스','Naver · Google 업무 도구',[
['ausomail','AUSOAI Mail','작성·저장·취소·EML','auso'],['naver-mail','Naver Mail','메일 확인·작성','Green'],['gmail','Gmail','메일 확인·작성','Coral'],['outlook','Outlook','메일·캘린더','Blue'],['gdrive','Google Drive','파일·공유','Blue'],['mybox','Naver MYBOX','클라우드·백업','Green','https://mybox.naver.com/'],['gdocs','Google Docs','문서 작성','Blue'],['sheets','Google Sheets','표·데이터','Green'],['slides','Google Slides','발표자료','Gold'],['gforms','Google Forms','설문·신청서','Violet','https://forms.google.com/'],['gcalendar','Google Calendar','일정·약속','Blue','https://calendar.google.com/'],['navercalendar','Naver Calendar','일정 보기','Green','https://calendar.naver.com/'],['gkeep','Google Keep','메모·체크','Gold','https://keep.google.com/'],['gphotos','Google Photos','사진·백업','Pink','https://photos.google.com/'],['gmeet','Google Meet','화상회의','Cyan']]],
['search','검색 · 소통 · 이동','자주 쓰는 서비스 · 앱·웹 연결',[
['naver','네이버','검색·뉴스·카페','Green'],['google','Google','검색·웹','Blue'],['youtube','YouTube','영상·채널','Coral'],['instagram','Instagram','콘텐츠·홍보','Pink'],['facebook','Facebook','페이지·홍보','Blue'],['kakao','KakaoTalk','대화·공유','Gold'],['translate','Google Translate','문서·화면·다국어','Cyan'],['papago','Papago','네이버 번역','Green','https://papago.naver.com/'],['navermap','Naver Map','길안내·장소','Green'],['gmaps','Google Maps','지도·해외 이동','Blue'],['weather','날씨','현재·주간 날씨','Cyan','https://weather.naver.com/']]],
['business','업무 · 비즈니스','고객 · 결제 · 물류 · 판매 · 광고',[
['crm','고객관리 CRM','고객·주문·메모','auso'],['library','자료실','문서·사진·영상','auso'],['pg','음성 PG','결제·정산 데모','auso'],['logistics','AI 물류','배송·물류 허브','auso'],['smartbuy','Smart Buy','멀티 제품 비교','auso'],['coupang','쇼핑','상품·주문','Gold'],['adwords','광고 키워드','분석·비교검색','auso'],['insurance','보험','상담·고객관리','Green','https://naruitda-insurance.kwonkiil.chatgpt.site/'],['encar','자동차','신차·중고·시세','Blue','https://www.encar.com/'],['travel','여행','항공·숙박·일정','Pink','https://www.google.com/travel/']]],
['more-ai','추가 앱 · AI·음성','같은 앱은 한 번만 표시',[
['chatgpt','ChatGPT','AI 대화','Green'],['gemini','Gemini','AI 대화','Blue'],['notebook','Notebook','기존 앱 연결','Blue',''],['elevenlabs','ElevenLabs','음성 작업','Violet','https://elevenlabs.io/'],['suno','Suno','음악 제작','Gold','https://suno.com/'],['clova','클로바노트','녹음·기록','Cyan','https://clovanote.naver.com/']]],
['more-social','추가 앱 · 소통·회의','메신저 · 채널 · 화상회의',[
['line','LINE','메신저','Green','https://line.me/ko/'],['whatsapp','WhatsApp','메신저','Green','https://www.whatsapp.com/'],['telegram','Telegram','메신저','Blue','https://web.telegram.org/'],['threads','Threads','소통·게시물','Violet','https://www.threads.net/'],['x','X','소통·게시물','Blue'],['tiktok','TikTok','영상·채널','Coral','https://www.tiktok.com/'],['ytstudio','YouTube Studio','채널 관리','Coral','https://studio.youtube.com/'],['zoom','Zoom','화상회의','Blue'],['webex','Webex','화상회의','Cyan','https://www.webex.com/']]],
['more-work','추가 앱 · 문서·제작','문서 · 클라우드 · 음원 편집',[
['onedrive','OneDrive','파일·클라우드','Blue'],['googleone','Google One','저장공간 관리','Gold','https://one.google.com/'],['polaris','Polaris Office','문서 편집','Blue','https://www.polarisoffice.com/'],['super-sound','Super Sound','기존 음원 편집 앱','Violet','']]],
['more-life','추가 앱 · 생활·업무','지도 · 공공서비스 · 결제 앱 바로가기',[
['kakaonavi','카카오내비','기존 길안내 앱','Gold',''],['srt','SRT','기차·이동','Pink','https://etk.srail.kr/'],['gov24','정부24','공공서비스','Blue'],['hometax','홈택스','국세청 서비스','Blue'],['naverpay','네이버페이','결제 앱·웹','Green','https://new-m.pay.naver.com/'],['cgv','CGV','영화·예매','Coral','https://www.cgv.co.kr/'],['melashopping','Melaleuca Shopping','사랑방과 별도 쇼핑 앱','Green',''],['grow','GROW','기존 앱 연결','Green','']]],
['more-dev','추가 앱 · 개발','기존 도구를 한곳에서 열기',[
['netlify','Netlify','사이트 관리','Cyan','https://app.netlify.com/'],['playconsole','Play Console','앱 배포 관리','Blue'],['github','GitHub','개발·소스','Violet'],['vercel','Vercel','사이트 관리','Blue']]],
['project','AUSOAI 프로젝트 · 시스템','기존 항목 유지 · 추가 프로젝트는 아래에',[
['ausoai','AUSOAI Portal','플래시·홍보영상·기존 포털','auso'],['utility','AUSOAI Utility','업무 목차·실사용 허브','auso'],['legacy','AUSOAI 구버전','기존 설치본·복구용','auso'],['reverse12','Reverse12','사업자 통합앱','Violet'],['melaleuca','멜라루카 사랑방','사랑방·고객','Green'],['naru','나루 모빌리티','탁송·관제','Blue'],['revenue','6축 수익모델','비즈니스 구조','auso'],['system','음성 설정','목소리·응답모드','auso'],['protools','전체 전문기능','확장 카테고리','auso'],['share','공유','사이트 공유','auso'],['hub','홈으로','AUSOAI 홈','auso'],['veliqo','벨리코 화상','회의장·첫 화면','Violet'],['namgu','대구 남구를 잇다','기존 프로젝트','Blue'],['health','건강을 잇다','기존 프로젝트','Green'],['nareul','나를잇다','기존 프로젝트','Cyan'],['vitda','VYDITA AI Studio','V잇다 · 기존 작업','Violet'],['excellent','엑설런트','고도화 작업','Gold'],['waaxxss','왁시스 WAAXXSS','기존 제품·작업','Gold'],['ninja','NINJA EV 탁송','기존 탁송 프로젝트','Blue'],['ownerform','OWNER FORM CENTER','기존 신청서 작업','Cyan']]]];
const nativeFiles={ausomail:'ausoai-mail.html',crm:'owner-reverse12.html#customers',library:'owner-reverse12.html#docs',smartbuy:'smart-buy.html',adwords:'ad-keyword-studio.html',revenue:'business-revenue.html',protools:'ausoai-pro-categories.html'};
const nativeUris={pg:'voicehub://pg',logistics:'voicehub://logistics',utility:'voicehub://openapp?package=com.ausoai.voice.utility',legacy:'voicehub://openapp?package=com.ausoai.voice'};
const symbols={insurance:'INS',reverse12:'R12',sinternet:'SAMSUNG',snotes:'SAMSUNG',weather:'날씨',excellent:'엑설런트',veliqo:'벨리코'};
const extraBrands={gforms:'logos/google-forms',gcalendar:'logos/google-calendar',telegram:'logos/telegram',threads:'simple-icons/threads',tiktok:'logos/tiktok-icon'};
const meta=new Map();for(const g of groups)for(const r of g[3]){if(meta.has(r[0]))throw Error('Duplicate hub id: '+r[0]);meta.set(r[0],{id:r[0],title:r[1],sub:r[2],theme:r[3],url:r[4],group:g[0]})}
function readLink(id){try{return safe(localStorage.getItem('ausoai-link-'+id)||'')}catch{return ''}}
function setup(id){const m=meta.get(id);if(!m)return;const d=$('#dialog'),b=$('#dialogBody');$('#dialogTitle').textContent=m.title+' 연결';b.innerHTML='<p>기존 앱이나 사이트로 연결하는 항목입니다. 현재 브라우저에서 자동 실행할 주소가 등록되지 않았습니다.</p>'+(nativeUris[id]?'<p><a class="btn" href="'+esc(nativeUris[id])+'">설치된 AUSOAI에서 열기</a></p>':'')+'<label>기존 사이트 주소<input id="restore-url" type="url" placeholder="https://" autocomplete="off" value="'+esc(readLink(id))+'"></label><p><button class="btn primary" id="restore-link-save">이 기기에 연결 저장</button></p><p class="note">주소만 이 브라우저에 저장합니다. 로그인·인증·결제는 원래 앱에서 직접 진행합니다.</p>';if(d.open)d.close();d.showModal();$('#restore-link-save').onclick=()=>{const u=safe($('#restore-url').value);if(!u){$('#restore-url').setCustomValidity('https:// 주소를 확인해 주세요.');$('#restore-url').reportValidity();return}try{localStorage.setItem('ausoai-link-'+id,u);const it=window.HUB_TEST.items.find(i=>i.id===id);if(it)it.url=u;d.close()}catch{$('#restore-url').setCustomValidity('기기 저장에 실패했습니다.');$('#restore-url').reportValidity()}}}
function icon(m){const id=m.id,im=A[id]||(['naver-mail','navermap'].includes(id)?A.naver:'');if(im)return '<img class="restoreLogo" src="'+esc(im)+'" alt="'+esc(m.title)+' 로고">';if(m.theme==='auso'&&A.ausoai)return '<img class="restoreLogo" src="'+esc(A.ausoai)+'" alt="AUSOAI 로고">';if(id==='sinternet'||id==='snotes')return '<span class="symbol samsungWordmark">SAMSUNG</span>';const source=window.HUB_TEST.items.find(x=>x.id===id);let brand=extraBrands[id]||source?.brand;if(id==='chrome')brand='logos/chrome';if(brand&&brand!=='chrome')return '<img class="restoreLogo" src="https://api.iconify.design/'+esc(brand)+'.svg" alt="'+esc(m.title)+' 로고" data-real-brand="1">';return '<span class="symbol" title="원본 로고 추가 필요">'+esc(symbols[id]||m.title)+'</span>'}
function renderSections(){if(!home||!home.isConnected)return;const root=home.querySelector('#sections');if(!root)return;root.innerHTML=groups.filter(g=>selected==='all'||g[0]===selected||(selected==='more'&&g[0].startsWith('more-'))).map(g=>'<section class="restoreGroup" data-section="'+g[0]+'" aria-label="'+esc(g[1])+'"><div class="intro"><h2>'+esc(g[1])+'</h2><small>'+esc(g[2])+'</small></div><div class="grid">'+g[3].map(r=>{const m=meta.get(r[0]),isProject=window.HUB_TEST.projects.some(p=>p.id===m.id);return '<article class="tile '+(m.theme==='auso'?'auso':'t'+m.theme)+'" data-item="'+m.id+'"><button class="tilebutton" data-run="'+m.id+'" title="'+esc(m.title)+'" aria-label="'+esc(m.title)+'"><span class="visual"><span class="logoPlate">'+icon(m)+'</span></span><span class="caption"><b class="tilename">'+esc(m.title)+'</b><small class="tilesub">'+esc(m.sub)+'</small></span></button>'+(isProject?'<a class="editLink" href="#project/'+m.id+'" aria-label="'+esc(m.title)+' 표지·로고 편집">편집</a>':'')+'</article>'}).join('')+'</div></section>').join('');root.querySelectorAll('img[data-real-brand]').forEach(img=>{img.onerror=()=>{img.hidden=true;const s=document.createElement('span');s.className='symbol';s.textContent='로고';img.after(s)}});mirrorMic()}
function mirrorMic(){const active=!!$('#micbtn')?.classList.contains('listening'),e=home?.querySelector('[data-item="mic"]');if(e&&e.classList.contains('listening')!==active)e.classList.toggle('listening',active)}
function setChips(){home?.querySelectorAll('[data-restore-cat]').forEach(b=>{b.classList.toggle('active',b.dataset.restoreCat===selected);b.setAttribute('aria-pressed',String(b.dataset.restoreCat===selected))})}
function reconcile(){queued=false;const shell=$('#app > .shell');if(!shell||!window.HUB_TEST)return;const fresh=home!==shell;home=shell;if(fresh){selected='all';home.dataset.restored='R2';const brand=home.querySelector('.brandbar');brand.innerHTML='<img class="brandimg" src="'+esc(A.ausoai)+'" alt="AUSOAI"><div class="brandtext"><h1>AUSOAI Global · Work Hub</h1><p>매일 쓰는 기능을 터치 · 문자 · 음성으로 같은 방식으로 실행</p></div><button class="home" id="restorehome">홈</button>';$('#restorehome').onclick=()=>{selected='all';renderSections();setChips();window.scrollTo(0,0)};const input=$('#query');if(input)input.placeholder='예: 지메일 열어 / 일정 열어 / 사진 편집 / PG / 네이버 지도';const nav=home.querySelector('.filters');nav.innerHTML='';for(const [id,label] of [['all','전체'],['today','오늘'],['edit','편집'],['mail','메일·오피스'],['search','검색·SNS'],['business','비즈니스'],['project','프로젝트'],['more','추가 앱']]){const b=document.createElement('button');b.className='chip';b.dataset.restoreCat=id;b.textContent=label;b.onclick=()=>{selected=id;setChips();renderSections()};nav.append(b)}setChips();const mic=$('#micbtn');if(mic)new MutationObserver(mirrorMic).observe(mic,{attributes:true,attributeFilter:['class']});const hint=document.createElement('p');hint.className='restoreHint';hint.textContent='작은 컬러 카드 · 기존 서비스 로고 · 핀치 확대/축소 · 상하 스크롤';nav.after(hint);home.querySelector('.foot').innerHTML='<div>AUSOAI Global · Practical Voice Work Environment<br><small>R2 · 기존 크기 복원 · 로고 적용 · 중복 정리</small></div>';renderSections()}else if(!home.querySelector('.restoreGroup'))renderSections();mirrorMic()}
function init(){if(initialized||!window.HUB_TEST)return;initialized=true;const originalChrome=document.querySelector('[data-item="chrome"] svg');if(originalChrome)A.chrome='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(new XMLSerializer().serializeToString(originalChrome));const {projects,items}=window.HUB_TEST;for(const [id,title] of [['utility','AUSOAI Utility'],['legacy','AUSOAI 구버전'],['ninja','NINJA EV 탁송'],['ownerform','OWNER FORM CENTER']])if(!projects.some(p=>p.id===id))projects.push({id,title,sub:'기존 프로젝트',url:'',cat:'project',project:true});for(const p of projects){const m=meta.get(p.id);if(m){p.title=m.title;p.sub=m.sub}}for(const m of meta.values()){if(projects.some(p=>p.id===m.id))continue;let it=items.find(i=>i.id===m.id);if(!it){it={id:m.id,title:m.title,sub:m.sub,cat:m.group,icon:'globe',url:''};items.push(it)}it.title=m.title;it.sub=m.sub;if(m.url!==undefined)it.url=m.url;if(readLink(m.id))it.url=readLink(m.id);if(nativeFiles[m.id]||nativeUris[m.id])it.url=readLink(m.id)}
$('#app').addEventListener('click',e=>{const btn=e.target.closest('[data-run]');if(!btn||!home?.contains(btn))return;const id=btn.dataset.run;if(id==='share'){e.preventDefault();e.stopImmediatePropagation();if(navigator.share)navigator.share({title:'AUSOAI Global · Work Hub',url:location.href.split('#')[0]}).catch(()=>{});else navigator.clipboard?.writeText(location.href.split('#')[0]);return}const p=projects.find(p=>p.id===id);if(p){const u=readLink(id)||safe(p.url);if(u){e.preventDefault();e.stopImmediatePropagation();const a=document.createElement('a');a.href=u;a.target='_blank';a.rel='noopener noreferrer';a.click()}return}if(nativeFiles[id]||nativeUris[id]||['notebook','super-sound','kakaonavi','melashopping','grow'].includes(id)){const i=items.find(i=>i.id===id);if(!i?.url){e.preventDefault();e.stopImmediatePropagation();setup(id)}}},true);
const ob=new MutationObserver(()=>{if(!queued){queued=true;queueMicrotask(reconcile)}});ob.observe($('#app'),{childList:true,subtree:true});reconcile();window.HUB_RESTORED={version:'R2',groups,meta,originalCount:69,get visibleCount(){return $('#app')?.querySelectorAll('[data-item]').length||0}}}
function start(){if(window.HUB_TEST)init();else setTimeout(start,20)}
const style=document.createElement('style');style.textContent=`
body:has(.shell[data-restored]){background:radial-gradient(circle at 3% 0%,rgba(46,224,190,.24),transparent 25%),radial-gradient(circle at 95% 5%,rgba(91,137,255,.22),transparent 27%),radial-gradient(circle at 72% 38%,rgba(255,113,173,.10),transparent 24%),linear-gradient(160deg,#fafffe 0,#eefaf6 48%,#eef4ff 100%)}
.shell[data-restored]{max-width:1180px;padding:calc(8px + env(safe-area-inset-top)) 8px calc(20px + env(safe-area-inset-bottom));font-family:'Noto Sans KR',system-ui,sans-serif;color:#102f32}
.shell[data-restored] .brandbar{position:relative;display:flex;gap:8px;align-items:center;padding:7px 8px;margin:0 0 7px;border:1px solid rgba(255,255,255,.72);border-radius:17px;background:rgba(248,255,253,.91);box-shadow:0 9px 24px rgba(25,74,78,.1)}
.shell[data-restored] .brandbar .brandimg{width:38px;height:38px;flex:0 0 38px;border-radius:12px}.brandtext{flex:1;min-width:0}
.shell[data-restored] .brandbar h1{font-size:12.5px;letter-spacing:.025em;line-height:1.25}.shell[data-restored] .brandbar p{font-size:7.4px;line-height:1.5;margin-top:2px;color:#6e8888}.shell[data-restored] .home{height:40px;min-width:48px;border:0;border-radius:12px;background:linear-gradient(135deg,#d9fff3,#dce9ff);color:#175b59;font-weight:900;font-size:13px}
.shell[data-restored] .command{display:flex;gap:6px;margin:0 0 6px;padding:0;background:none;border:0;border-radius:0;box-shadow:none}
.shell[data-restored] .command input{height:42px;flex:1;min-width:0;border:0;border-radius:14px;background:rgba(255,255,255,.96);padding:0 12px;font-size:11.5px;outline:1px solid rgba(53,175,153,.14);box-shadow:0 5px 16px rgba(29,93,91,.07)}
.shell[data-restored] .command>.btn{height:42px;min-height:42px;min-width:58px;border:0;border-radius:14px;background:linear-gradient(135deg,#28cbb0,#5e9df8);color:#fff;font-weight:950;font-size:13px;padding:0 10px}
.shell[data-restored] #micbtn{position:absolute;width:1px;height:1px;min-height:0;padding:0;overflow:hidden;clip-path:inset(50%);pointer-events:none}
.shell[data-restored] .filters{display:flex;gap:5px;overflow:auto;padding:1px 1px 7px;margin:0;scrollbar-width:none}
.shell[data-restored] .chip{height:31px;min-height:31px;border:0;border-radius:999px;padding:0 10px;background:rgba(255,255,255,.82);color:#51716f;font-size:8px;font-weight:850;box-shadow:0 3px 11px rgba(24,91,84,.06)}.shell[data-restored] .chip.active{background:#123c46;color:#e9fffb}
.restoreHint{font-size:7.4px;color:#708e8b;margin:0 2px 7px;line-height:1.5}.shell[data-restored] .intro{display:flex;align-items:end;justify-content:space-between;margin:10px 2px 6px;gap:5px}.shell[data-restored] .intro h2{font-size:9.4px;letter-spacing:.04em;line-height:1.3}.shell[data-restored] .intro small{font-size:6.8px;color:#789492;text-align:right;line-height:1.3}
.shell[data-restored] .grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px}
.shell[data-restored] .tile{--a:#d9fff0;--b:#dcecff;position:relative;min-height:79px;border-radius:14px;overflow:hidden;text-decoration:none;color:#153c3c;background:rgba(255,255,255,.91);box-shadow:0 5px 17px rgba(33,92,88,.08);border:1px solid rgba(255,255,255,.74)}
.shell[data-restored] .tilebutton{display:block;text-align:left;width:100%;height:100%;padding:0;background:transparent;color:inherit;border:0}.shell[data-restored] .tilebutton:active{transform:scale(.955)}
.shell[data-restored] .visual{aspect-ratio:auto;height:45px;width:100%;display:grid;place-items:center;background:linear-gradient(145deg,var(--a),var(--b));position:relative;border:0;box-shadow:none;border-radius:0;transform:none}
.logoPlate{width:34px;height:34px;border-radius:10px;background:rgba(255,255,255,.88);display:grid;place-items:center;box-shadow:0 3px 10px rgba(25,72,79,.1);overflow:hidden}.logoPlate .restoreLogo{width:25px;height:25px;max-width:25px;object-fit:contain;border-radius:5px}.logoPlate svg{width:27px;height:27px;display:block}.logoPlate .symbol{font-size:9px;font-weight:900;letter-spacing:-.05em;color:#167a75;max-width:32px;max-height:30px;overflow:hidden;text-align:center;line-height:1.2}.logoPlate .samsungWordmark{font-size:4px;color:#193b83;letter-spacing:.15px;font-family:Arial,sans-serif;font-weight:900}
.shell[data-restored] .caption{display:block;padding:5px 6px 6px}.shell[data-restored] .tilename{display:block;font-size:9px;line-height:1.15;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin:0;font-weight:700}.shell[data-restored] .tilesub{display:block;margin-top:2px;min-height:0;font-size:6.4px;line-height:1.2;color:#718d8a;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-align:left;padding-right:0}
.shell[data-restored] .tMint{--a:#d8fff0;--b:#ccecff}.shell[data-restored] .tBlue{--a:#d9ebff;--b:#e1ddff}.shell[data-restored] .tPink{--a:#ffe0ec;--b:#ffe8c9}.shell[data-restored] .tGold{--a:#fff0bd;--b:#e7e0ff}.shell[data-restored] .tGreen{--a:#d9f9e4;--b:#dffff6}.shell[data-restored] .tCyan{--a:#d7f8ff;--b:#d5ffe5}.shell[data-restored] .tCoral{--a:#ffe2d1;--b:#ffe0ed}.shell[data-restored] .tViolet{--a:#e8ddff;--b:#d8e9ff}
.shell[data-restored] .auso{background:linear-gradient(165deg,#061a32,#0b3652);color:#f2ffff;border-color:rgba(82,240,225,.16)}.shell[data-restored] .auso .visual{background:radial-gradient(circle at 28% 24%,#286b8a,#08182f 70%)}.shell[data-restored] .auso .tilesub{color:#a7d6d1}
.editLink{position:absolute;right:5px;bottom:4px;font-size:6px;background:rgba(255,255,255,.92);color:#175b59;border-radius:4px;padding:2px 3px;line-height:1}.tile:has(.editLink) .tilesub{padding-right:16px}
.shell[data-restored] .foot{display:block;border:0;text-align:center;margin-top:18px;padding:13px 4px 2px;color:#789693;font-size:7px;line-height:1.7}.shell[data-restored] .foot small{font-size:6px}.shell[data-restored] .voicehud{font-size:8px;padding:5px 8px;background:rgba(255,255,255,.72);border-radius:10px;margin-bottom:5px}.shell[data-restored] .voicehud .vstate{font-size:6.6px}.tile.listening .logoPlate{animation:heartbeat 1.65s ease-in-out infinite;box-shadow:0 0 0 5px #3edde128}
@media(prefers-reduced-motion:reduce){.tile.listening .logoPlate{animation:none;outline:2px solid #37cdb0}}
`;document.head.append(style);
function loadAtlas(){const d=window.HUB_LOGO_ATLAS;if(!d)return;const im=new Image;im.onload=()=>{const c=document.createElement('canvas');c.width=c.height=d.size;const ctx=c.getContext('2d');d.ids.forEach((id,i)=>{ctx.clearRect(0,0,d.size,d.size);ctx.drawImage(im,(i%d.cols)*d.size,Math.floor(i/d.cols)*d.size,d.size,d.size,0,0,d.size,d.size);A[id]=c.toDataURL('image/png')});if(home?.isConnected)renderSections()};im.src=d.image}
if(window.HUB_LOGO_ATLAS)loadAtlas();else{const ls=document.createElement('script');ls.src=new URL('restore-logos.js',BASE);ls.onload=loadAtlas;document.head.append(ls)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
